### PR TITLE
Added a file explore_taxa.html.haml as per TODO in application.html.haml

### PR DESCRIPTION
**Pull request by aka001**
@JRice  Kindly review this pr.

### CODE REVIEW

**Comment by JRice** [comment]
Thanks for the submission, but this wasn't the intended solution here. Sorry for the confusion. Comments are on the commit.

Closing.

**Comment by aka001** [comment]
@JRice Ya I got it. Thank you for the detailed comments. I will update this pr accordingly.

**Comment by aka001** [comment]
@JRice I am unable to make any changes to this pr since it's closed. Can you please open it, so that I can update it based on your instructions?

**Comment by JRice** [comment]
Looks like I cannot; the branch was either force-pushed or recreated. Sorry for the trouble.

**Comment by aka001** [comment]
@JRice No problem. I have created another pr https://github.com/EOL/eol/pull/111 . Kindly review it.

**Pull request closed without merging**
